{{- if .Values.global.ingress.nginx.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "appflowy-gotrue.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  {{- with .Values.global.ingress.nginx.extraAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.global.ingress.nginx.className }}
  rules:
    - host: {{ .Values.global.externalHost }}
      http:
        paths:
          - path: /gotrue(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "appflowy-gotrue.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
  {{- if .Values.global.ingress.nginx.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.global.externalHost }}
      secretName: {{ .Values.global.ingress.nginx.tls.secretName }}
  {{- end }}
{{- end }}
